name: YouTube Auto Uploader

on:
  schedule:
    - cron: "0 10 * * *"   # daily 10 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Restore client_secret.json
        run: echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json

      - name: Restore token.json
        run: echo "${{ secrets.TOKEN_JSON }}" > token.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: uploader.log
